packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@google/genai': true
  bun: true
  electron: true
  esbuild: true
  node-pty: true
  onnxruntime-node: true
  openclaw: true
  protobufjs: true
  sharp: true
  tree-sitter-bash: true
