packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@google/genai': true
  bun: true
  electron: true
  esbuild: true
  node-pty: true
  onnxruntime-node: set this to true or false
  protobufjs: true
  sharp: true
