import { DEFAULT_ACCESS_MODE } from "@chengxiaobang/shared";
import type {
  FeishuConfig,
  FeishuStatus,
  Message,
  ModelDebugRecord,
  PluginSummary,
  ProviderConfig,
  Project,
  ReasoningMode,
  RunRecord,
  ScheduledTask,
  Session,
  SideChatSummary,
  SkillSummary,
  SlashCommand,
  StreamEvent,
  TokenUsage,
  ToolActivity,
  ToolCall,
  WebSearchConfig,
  WechatConfig,
  WechatStatus
} from "@chengxiaobang/shared";
import { DEFAULT_LOCALE, type Locale } from "../i18n";
import { DEFAULT_CODE_PREVIEW_SETTINGS } from "../lib/code-preview-settings";
import { normalizeOnboardingProfile, type OnboardingProfile } from "../../common/profile";
import { DEFAULT_RIGHT_PANEL_WIDTH } from "./helpers/right-panel";
import type {
  AppState,
  Attachment,
  ComposerDraft,
  ComposerDraftScope,
  ModelSelection,
  NotificationToast,
  OnboardingStep,
  PreviewFileState,
  ProjectSortMode,
  QueuedRunItem,
  RightPanelMode,
  RightPanelSessionState,
  RightPanelTab,
  TerminalEntry,
  Theme,
  View
} from "./types";

export const initialState =  {
  projects: [] as Project[],
  sessions: [] as Session[],
  messages: [] as Message[],
  toolHistory: [] as ToolCall[],
  runHistory: [] as RunRecord[],
  modelDebugRecords: [] as ModelDebugRecord[],
  providers: [] as ProviderConfig[],
  slashCommands: [] as SlashCommand[],
  activeSessionId: undefined as string | undefined,
  activeProjectId: undefined as string | undefined,
  providerId: undefined as string | undefined,
  model: undefined as string | undefined,
  reasoningMode: undefined as ReasoningMode | undefined,
  homeModelSelection: {} as ModelSelection,
  planMode: false,
  accessMode: DEFAULT_ACCESS_MODE,
  view: "home" as View,
  paletteOpen: false,
  onboardingOpen: false,
  onboardingCompleted: false,
  onboardingDismissed: false,
  onboardingStep: "welcome" as OnboardingStep,
  onboardingProfile: normalizeOnboardingProfile({ primaryUse: "both" }) as OnboardingProfile,
  notice: undefined as string | undefined,
  notificationToasts: [] as NotificationToast[],
  input: "",
  attachments: [] as Attachment[],
  composerDraftsByScope: {} as Record<ComposerDraftScope, ComposerDraft>,
  activeComposerDraftScope: "home" as ComposerDraftScope,
  fileSuggestions: [] as string[],
  streamText: "",
  thinking: "",
  thinkingStartedAt: undefined as number | undefined,
  thinkingDurationMs: undefined as number | undefined,
  activeRunStartedAt: undefined as number | undefined,
  events: [] as StreamEvent[],
  streamingPlan: undefined,
  toolActivity: undefined as ToolActivity | undefined,
  runningTool: undefined as ToolCall | undefined,
  runningToolVisualHolds: {},
  pendingTool: undefined as ToolCall | undefined,
  isRunning: false,
  runningSessionsById: {} as Record<string, true>,
  runningRunSessionById: {} as Record<string, string>,
  runningTaskIds: {} as Record<string, true>,
  activeRunId: undefined as string | undefined,
  activeRunClientRequestId: undefined as string | undefined,
  progressPanelOpen: false,
  progressPanelAutoOpenedRunId: undefined as string | undefined,
  activeRunModel: undefined as
    | { providerId?: string; model: string; reasoningMode?: ReasoningMode }
    | undefined,
  activeRunLastAssistant: undefined as Message | undefined,
  queuedRunsBySession: {} as Record<string, QueuedRunItem[]>,
  pausedRunQueuesBySession: {} as Record<string, true>,
  lastUsage: undefined as TokenUsage | undefined,
  lastRunModel: undefined as
    | { providerId?: string; model: string; reasoningMode?: ReasoningMode }
    | undefined,
  runMeta: {} as Record<
    string,
    {
      durationMs: number;
      promptTokens: number;
      completionTokens: number;
      model: string;
      reasoningMode?: ReasoningMode;
    }
  >,
  sidebarOpen: true,
  projectSortMode: "recent" as ProjectSortMode,
  sidebarProjectsExpanded: false,
  sidebarExpandedProjectSessionIds: {} as Record<string, true>,
  sidebarUngroupedExpanded: false,
  sidebarProjectsPage: { loaded: 0, total: 0, hasMore: false },
  sidebarUngroupedSessionsPage: { loaded: 0, total: 0, hasMore: false },
  sidebarProjectSessionsPageByProjectId: {},
  rightPanelOpen: false,
  rightPanelMode: null as RightPanelMode | null,
  rightPanelTabs: [] as RightPanelTab[],
  rightPanelActiveTabId: undefined as string | undefined,
  rightPanelMaximized: false,
  rightPanelWidth: DEFAULT_RIGHT_PANEL_WIDTH,
  previewFile: undefined as PreviewFileState | undefined,
  filePreviewEntrySource: undefined,
  browserUrl: "",
  rightPanelBySession: {} as Record<string, RightPanelSessionState>,
  gitRefreshTokenByProjectId: {} as Record<string, number>,
  sideChatsByMessageId: {} as Record<string, SideChatSummary>,
  activeSideChatAnchorMessageId: undefined as string | undefined,
  terminalEntries: [] as TerminalEntry[],
  terminalRunning: false,
  feishuConfig: undefined as FeishuConfig | undefined,
  feishuStatus: undefined as FeishuStatus | undefined,
  wechatConfig: undefined as WechatConfig | undefined,
  wechatStatus: undefined as WechatStatus | undefined,
  webSearchConfig: undefined as WebSearchConfig | undefined,
  tasks: [] as ScheduledTask[],
  skills: [] as SkillSummary[],
  skillsAddRequested: false,
  pendingSettingsSection: undefined as string | undefined,
  plugins: [] as PluginSummary[],
  theme: "system" as Theme,
  codePreviewSettings: DEFAULT_CODE_PREVIEW_SETTINGS,
  locale: DEFAULT_LOCALE as Locale,
  clientReady: false
};
